# Generated by Django 3.2.4 on 2021-06-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood_app', '0005_alter_neighbourhood_occupants'),
        ('user', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_hood', to='neighborhood_app.neighbourhood')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user.profile')),
            ],
        ),
    ]
