# Generated by Django 3.2.4 on 2021-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_app', '0003_neighbourhood_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(default=''),
        ),
    ]
