# Generated by Django 3.2.4 on 2021-06-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_image'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='admin',
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
