# Generated by Django 3.2.4 on 2021-06-04 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Profile Picture'),
        ),
    ]
